
# Maximum line length
column_width = 150

# Indent type: "Tabs" or "Spaces"
indent_type = "Spaces"

# Indent width
indent_width = 2

# Quote style: "AutoPreferDouble", "AutoPreferSingle", "AlwaysDouble", "AlwaysSingle"
quote_style = "AutoPreferDouble"

# Call parentheses style: "Avoid", "Always"
call_parentheses = "Always"
collapse_simple_statement = "Never"

